// ── PASSAGES ─────────────────────────────────────────────────────────────────
// Organised by time mode. Target typist: ~50 WPM.
//   30s pool  → 40-60 words  (30 passages)
//    1m pool  → 80-120 words (20 passages)
//    3m pool  → 220-300 words (15 passages)
//
// Sources: public domain — Baum, Carroll, Wells, Burroughs, Stoker, Doyle.

const PASSAGES = {

  // ── 30 s ──────────────────────────────────────────────────────────────────
  30: [
    // Wizard of Oz — Baum
    `Dorothy lived in the midst of the great Kansas prairies, with Uncle Henry, who was a farmer, and Aunt Em, who was the farmer's wife. Their house was small, for the lumber to build it had to be carried by wagon many miles.`,

    `The cyclone had set the house down, very gently, in the midst of a country of marvellous beauty. There were lovely patches of greensward all about, with stately trees bearing rich and luscious fruits.`,

    `The road to the City of Emeralds is paved with yellow brick, so you cannot well miss it. When you get to Oz, do not be afraid of the great Wizard, but tell your story and ask him to help you.`,

    `Toto did not really care whether he was in Kansas or the Land of Oz so long as Dorothy was with him; but he knew the little girl was unhappy, and that made him unhappy too.`,

    `The Scarecrow watched the Tin Woodman chop the trees into firewood with a great deal of interest. He had never seen a man work so hard without growing tired, and it seemed to him quite wonderful.`,

    // Alice in Wonderland — Carroll
    `Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do. Once or twice she had peeped into the book her sister was reading, but it had no pictures in it.`,

    `Down, down, down. Would the fall never come to an end? There was nothing else to do, so Alice soon began talking again. Dinah will miss me very much tonight, she thought. I hope they remember her saucer of milk.`,

    `Curiouser and curiouser! cried Alice. She was so surprised that for the moment she quite forgot how to speak good English. Now I am opening out like the largest telescope that ever was. Goodbye, feet!`,

    `The Queen had only one way of settling all difficulties, great or small. Off with his head! she said, without even looking round. Alice thought she had never seen such a curious croquet-ground in all her life.`,

    `Alice had begun to think that very few things indeed were really impossible since she had fallen down that rabbit-hole and found herself in a world that seemed turned quite upside down.`,

    // The War of the Worlds — Wells
    `No one would have believed, in the last years of the nineteenth century, that this world was being watched keenly and closely by intelligences greater than man's and yet as mortal as his own.`,

    `The Martians were coming out of the cylinder. They were large, round, greyish creatures, with a peculiar V-shaped mouth with a pointed upper lip and no chin beneath. They had tentacles, about the mouth, and the eyes were extraordinary.`,

    `In the street people were running. A woman screamed. The road ahead of me glowed and flashed, and a hot wind rushed past. I turned and looked back at the common. The whole hillside was afire.`,

    `The gaslight was still burning, though it was now broad daylight. I found my wife in the kitchen with a loaf of bread and some cold ham. She had risen early, she said, because she could not sleep.`,

    // The Princess of Mars — Burroughs
    `I am a very old man; how old I do not know. Possibly I am a hundred, possibly more; but I cannot tell because I have never aged as other men age. When I was thirty I looked just as I do now.`,

    `As I stood upon the edge of the plateau I could see the valley below, stretching away into the distance. It was a peaceful, lovely scene, but I knew that beneath that calm lay danger beyond anything I had faced before.`,

    `The great Tharks were a warlike people, proud and fierce. They respected strength above all things, and a stranger who showed courage in their presence was treated as an equal, whatever his race or origin might be.`,

    `I was alone on the dead sea bottom, the nearest Martian miles away. Above me shone the moons of Barsoom, casting pale light over the ancient landscape. I had never felt so entirely at the mercy of a strange world.`,

    // Dracula — Stoker
    `The castle is on the very edge of a terrific precipice. A stone falling from the window would fall a thousand feet before striking anything. As far as the eye can reach is a sea of green tree tops.`,

    `I looked at the captain, and saw him tie up the wheel and lash it, then clasp his hands together as in prayer. A great wind arose, and the ship sailed on, guided as if by an unseen hand.`,

    `The Count smiled, and as his lips ran back over his teeth, I could see how sharp they were. He began then to speak in a low, quiet voice, and the words seemed to float in the heavy air of the room.`,

    // Sherlock Holmes — Doyle
    `It was a cold morning in late autumn. A dense fog rolled down between the lines of dun-coloured houses, and the opposing windows loomed like dark, shapeless blurs through the heavy yellow wreaths.`,

    `Holmes was working late into the night, surrounded by papers and chemical apparatus. I watched him from my chair by the fire, wondering as I often did what singular problem had captured his extraordinary mind this time.`,

    `You have been in Afghanistan, I perceive. The words were spoken quietly, almost carelessly, but they struck the stranger like a thunderbolt. He stared at the lean, hawk-faced man in the armchair with astonishment.`,

    `The game is afoot, Watson! Holmes cried, seizing his hat and coat. We have not a moment to lose if we are to catch the man before he disappears into the fog of the city once more.`,

    `It is a capital mistake to theorise before one has data, Holmes said. Insensibly one begins to twist facts to suit theories, instead of theories to suit facts. The method must always start with observation.`,

    `I had seen death in many forms, but nothing quite prepared me for what lay in that shuttered room. Holmes knelt beside the figure and examined it with his lens, his face utterly expressionless, his mind already racing ahead.`,

    `The Baker Street rooms were comfortable, if somewhat disordered. Papers lay everywhere, and the smell of tobacco hung in the air. Holmes sat in the middle of it all, perfectly still, his long fingers pressed together beneath his chin.`,

    `When you have eliminated the impossible, whatever remains, however improbable, must be the truth. Holmes rose from his chair and paced the length of the room twice before turning to face me with that familiar sharp gleam in his grey eyes.`,

    `The woman's scream had cut through the night like a blade. Within moments Holmes was at the window, then pulling on his coat. I took my revolver from the drawer without being asked and followed him down the stairs.`,
  ],

  // ── 1 m ───────────────────────────────────────────────────────────────────
  60: [
    // Wizard of Oz — Baum
    `Dorothy gazed thoughtfully at the Scarecrow, whose head was a small sack stuffed with straw, with eyes, nose and mouth painted on it to represent a face. An old, pointed blue hat that had belonged to some Munchkin was perched on the top of his head. He was mounted on a pole stuck among the stalks of a field of corn. Dorothy leaned her chin upon her hand and thought about it. His face seemed so comical to her that she laughed. Then she asked, Are you happy out here in this cornfield?`,

    `The Emerald City was built of green marble and studded everywhere with sparkling emeralds. Even the sky above the city had a green tint, and the rays of the sun were green when they shone upon the streets. Dorothy and her companions walked along streets paved with green marble and lined with beautiful green houses. Many people, all dressed in green clothes, came to stare at them, for strangers of any kind were unusual in the Emerald City, and these particular visitors were so extraordinary that everyone stopped to gaze at them.`,

    // Alice in Wonderland — Carroll
    `The table was a large one, but the three were all crowded together at one corner of it. No room! No room! they cried out when they saw Alice coming. There's plenty of room! said Alice indignantly, and she sat down in a large arm-chair at one end of the table. Have some wine, the March Hare said in an encouraging tone. Alice looked all round the table, but there was nothing on it but tea. I don't see any wine, she remarked. There isn't any, said the March Hare. Then it wasn't very civil of you to offer it, said Alice angrily.`,

    `Alice thought she had never seen such a curious croquet-ground in her life; it was all ridges and furrows; the balls were live hedgehogs, the mallets live flamingoes, and the soldiers had to double themselves up and stand on their hands and feet, to make the arches. The chief difficulty Alice found at first was in managing her flamingo: she succeeded in getting its body tucked away, comfortably enough, under her arm, with its legs hanging down, but generally, just as she had got its neck nicely straightened out, and was going to give the hedgehog a blow with its head, it would twist itself round and look up in her face.`,

    `Who are you? said the Caterpillar. Alice replied, rather shyly, I hardly know, sir, just at present — at least I know who I was when I got up this morning, but I think I must have been changed several times since then. What do you mean by that? said the Caterpillar sternly. Explain yourself! I can't explain myself, I'm afraid, sir, said Alice, because I'm not myself, you see. I don't see, said the Caterpillar. I'm afraid I can't put it more clearly, Alice replied very politely, for I can't understand it myself to begin with.`,

    // The War of the Worlds — Wells
    `I remember how jubilant Markham was at securing a new photograph of the planet for the illustrated paper he edited in those days. People in these latter times scarcely realise the abundance and enterprise of our nineteenth-century papers. For my own part, I was much occupied in learning to ride the bicycle, and busy upon a series of papers discussing the probable developments of moral ideas as civilisation progressed. One night, the first of a series of similar ones, I went for a walk with my wife. It was starlight and I explained the Signs of the Zodiac to her, and pointed out Mars, a bright dot of light creeping zenithward.`,

    `The cylinder was already opened in the centre of the pit, and from the middle of it came the pall of greenish smoke, lit by little flashes of yellowish-white metal. The whole area was full of people running hither and thither. At one time the road was packed with a screaming mob, and at another it was quite empty and desolate. Near the Woking station I fell in with an artilleryman, and found myself trying to recall the address of a friend I had there; then I turned back to see if I could catch the train that had just left.`,

    `The thunderclap, the flash of light, and the thud of the explosion were simultaneous. All around the pit was a blinding glare of green fire. The heat-ray had returned. I saw the common about me, tinted with fire, with little circles of flame where the Martians had touched. I turned and ran through the smoke-stained air, not daring to look behind me, knowing that the Martians were there, that at any moment the ray might swing again and I would be gone. I ran until my lungs burned and my legs gave way.`,

    // The Princess of Mars — Burroughs
    `I lay upon a yellow, moss-like substance, which covered the floor of the building to the depth of several inches. Covering me was some of the same material, which, very evidently, had been used for my bed while I was unconscious. I attempted to rise and, after several efforts, succeeded in getting upon my feet. Staggering to the window I gazed out upon a landscape that was strange and foreign. Red and yellow vegetation mixed with strange trees whose colours I had never before encountered. In the far distance a great range of mountains rose blue and hazy in the thin Martian air.`,

    `John Carter did not hesitate. As the green warrior raised his weapon, Carter sprang forward with a speed that astonished every eye in the great audience chamber. He covered the thirty feet between himself and the Thark in a single bound, for the lesser gravity of Mars lent his legs a power and swiftness he had never known on Earth. He disarmed the warrior before the crowd could so much as gasp, and stood there in the centre of the chamber, his eyes sweeping the assembled Tharks, daring any of them to make the next move.`,

    // Dracula — Stoker
    `I must have been asleep, for certainly if I had been fully awake I must have noticed the approach of such a remarkable place. In the gloom the courtyard looked of considerable size, and as several dark ways led from it under great round arches, it perhaps seemed bigger than it really is. I have not yet been able to see it by daylight. When the calèche stopped, the driver jumped down and held out his hand to assist me to alight. Again I could not but notice his prodigious strength. His hand actually seemed like a steel vice that could have crushed mine if he had chosen.`,

    `The castle is a veritable prison, and I am a prisoner. When I found that I was a prisoner, a sort of wild feeling came over me. I rushed up and down the stairs, trying every door and peering out of every window I could find; but after a little the conviction of my helplessness overpowered all other feelings. When I look back after a few hours I think I must have been mad for the time, for I behaved much as a rat does in a trap.`,

    `She came to me as if in a dream. I did not hear her footfall, nor see the door open. She was simply there, at the foot of my bed, and she was beautiful in a terrible way that made me want to cry out and yet remain perfectly still all at once. The moonlight fell across her face, and I saw then what she truly was, and I knew that I should never be the same again.`,

    // Sherlock Holmes — Doyle
    `It was a singular document. The paper was of a peculiar quality, the sort I have seldom encountered, and the ink had been applied by a hand that trembled with either age or agitation. Holmes studied it for a long time without speaking. I could see his eyes moving rapidly over the lines, then returning to certain words, then moving on again with the certainty of a man reading a map. Finally he set it down, placed his fingers together, and looked at me over his joined hands with that curious expression of calm excitement that I had come to associate with some of his most remarkable discoveries.`,

    `I had been in practice for some months, and my health had so far recovered that I was able to take moderately long walks and even to attempt a few exercises on the weights. One evening, returning from a long ramble, I found a visitor waiting for me. He was a tall, well-dressed man of about forty, with a heavy moustache and an alert, sharp-featured face. He rose as I entered and said that he had heard of my association with the famous Mr. Sherlock Holmes, and wished to consult me on a matter of the greatest urgency and delicacy.`,

    `Holmes had been bending for a long time over a low-power microscope. Now he straightened himself up and looked round at me in triumph. It is glue, Watson, he said. Extraordinarily common wood-glue, but applied at a very precise angle, and apparently quite recently. This single fact changes everything I had previously supposed about the case. You see, I had assumed our man worked alone. But glue of this kind requires two pairs of hands at the very least. We are not looking for one criminal, Watson. We are looking for two.`,

    `The fog was so dense that even the gas-lamps in the street were mere blurs of yellow light. Holmes walked ahead of me at his usual rapid pace, apparently utterly indifferent to the cold and the murk. He seemed to me in those moments to be not quite a creature of this world, but some sharp-edged instrument of reason that the rest of humanity had somehow conjured into being to solve the problems it could not solve itself.`,

    `My name is Sherlock Holmes. It is my business to know what other people don't know. The man before us smiled thinly and said that was a very fine boast. Holmes regarded him with that peculiar, half-amused expression I knew so well, and then proceeded, without hurry, to outline every particular of the man's morning routine, his profession, his recent travel, and the nature of the errand that had brought him to Baker Street. The smile did not return.`,

    `There was a letter in the morning post that Holmes seized upon with unusual eagerness. He read it twice, then laid it on the table and drummed his fingers upon the cloth in a rapid tattoo. Watson, he said at last, I think this case may prove to be the most interesting I have encountered in several years. I say may, because at present I understand almost nothing. And it is only when I understand almost nothing that the real possibilities begin to reveal themselves.`,

    `A man's true character is most plainly seen not in what he boasts of, but in the small things he imagines no one notices. The worn edge of a cuff, the angle at which a hat is placed, the particular hesitation before a certain kind of question. Holmes saw all of these things before the visitor had settled into his chair, and by the time the man had finished his opening sentence, Holmes had already formed the outline of an answer.`,
  ],

  // ── 3 m ───────────────────────────────────────────────────────────────────
  180: [
    // Wizard of Oz — Baum
    `Dorothy was a little girl who lived in the grey prairies of Kansas with her Uncle Henry and Aunt Em. The house was small and plain, for the lumber had to be carried by wagon many miles. When Dorothy stood in the doorway and looked around, she could see nothing but the great grey prairie on every side. Not a tree nor a house broke the broad sweep of flat country that reached the edge of the sky in all directions. The sun had baked the ploughed land into a grey mass, with little cracks running through it. Even the grass was not green, for the sun had burned the tops of the long blades until they were the same grey colour to be seen everywhere. When Aunt Em came there to live she was a young, pretty wife. The sun and wind had changed her, too. They had taken the sparkle from her eyes and left them a sober grey. They had taken the red from her cheeks and lips, and they were grey also. She was thin and gaunt, and never smiled now. When Dorothy, who was an orphan, first came to her, Aunt Em had been so startled by the child's laughter that she would scream and press her hand upon her heart whenever Dorothy's merry voice reached her ears.`,

    `The journey through the forest was long and the path was dark. The Cowardly Lion stayed very close to Dorothy's side, for even though he knew perfectly well that he was a coward, he did not like to admit it by running away. The Tin Woodman lifted his axe whenever strange sounds reached them from the shadows between the trees, and the Scarecrow did his best to walk in a straight line despite his somewhat unreliable legs. Dorothy herself was not frightened, for Toto was with her, and she had found in her short life that the presence of a small, faithful creature was worth more than a great deal of armour. They had been walking for what seemed many hours when the trees began to thin ahead of them and a pale light crept between the trunks. None of them spoke of the light, fearing that to name it would be to lose it, but they all walked a little faster, and even the Lion's enormous paws seemed to find a lighter footing on the forest floor. Then the last tree fell away and before them, stretching to the horizon, lay a great field of scarlet poppies, their blossoms nodding in a warm and drowsy wind.`,

    // Alice in Wonderland — Carroll
    `Alice had grown so large that she quite filled the little room, and could only see out of one window. When she had eaten a little more of the left-hand bit she came out and found a small house about four feet high. I wonder what they'll do next, thought Alice. If they had any sense, they'd take the roof off. After a minute or two they began moving about again, and Alice heard the Rabbit say, A barrowful will do, to begin with. This did not sound encouraging. A little later she heard it say, Well, I shan't go alone. I know I should be frightened. A small voice then replied to it, and soon another voice, saying that she would do. Alice next heard a scratching and a pattering, as of many little feet overhead, followed by a great crash, as if a dish or kettle had been flung hard against the floor. On all sides came running: Ow! Ow! Ow! And then silence. Alice waited, and then tried the door, but it would not open. There was no room to turn round in, and no room to sit down in. She knew she must find a way out or she should stay there forever.`,

    `The Mock Turtle looked at Alice with large eyes full of tears, but said nothing. It's all his fancy, that: he hasn't got no sorrow, said the Gryphon; and then to Alice: Have you seen a Mock Turtle? No, said Alice. We called him Tortoise because he taught us, said the Mock Turtle angrily; really you ought to be ashamed of yourself for asking such a simple question. How many hours a day did you do lessons? said Alice, trying to change the subject. Ten hours the first day, said the Mock Turtle, nine the next, and so on. What a curious plan! said Alice. That's the reason they're called lessons, the Gryphon remarked: because they lessen from day to day. This was quite a new idea to Alice, and she thought it over a little before she made her next remark. Then the eleventh day must have been a holiday? Exactly so, said the Mock Turtle. And how did you manage on the twelfth? asked Alice eagerly. That's enough about lessons, the Gryphon interrupted in a very decided tone. Tell her something about the games now.`,

    // The War of the Worlds — Wells
    `And this was the little world in which I moved. It seemed to me impossible to believe that any intelligence could be great enough, or ruthless enough, to treat it as a mere hunting ground. The country about was quiet and warm, the roads empty, the sky blue and clear. Birds sang in the trees; a dog lay sleeping in the sun before a garden gate. There was a smell of cut grass and honeysuckle on the air. A woman hung washing in a back garden, and two children played noisily in the lane beside her. I remember I kept thinking: how strange it is that these people do not know, that they walk and talk and laugh, that the world still moves and hums and breathes, while the Martians are coming. And then one of the cylinders fell on Woking, and the heat-ray touched the earth for the first time, and the smoke rose, and the screaming began in the streets below. And I knew that from that moment everything I had previously understood about the nature of our world and our safety in it was simply wrong. The Martians had not come to visit. They had come to conquer, and we had nothing to meet them with but our courage and our astonishment.`,

    `The evacuation of London was extraordinary to witness. Hundreds of thousands of people, on foot and on horseback, in wagons and carts, pressed northward and southward, east and west, out of the great city and into the country lanes. The roads became choked, then impassable. Tempers frayed and broke. Children were separated from their parents, old people fell and were not helped up again. The telegraph wires were burning. Trains had stopped running on most lines. Government had not failed so much as dissolved, simply ceased to be relevant in the face of something so utterly beyond its competence to address. I watched from a hillside as the refugees streamed past below me, and I thought of what Holmes had once said about the fragility of civilisation: that it was not a stone building but a conversation, and could be ended by anyone who chose to stop talking. The Martians had chosen. And all the accumulated arrangements of humanity, all its laws and manners and institutions, all the things by which we had distinguished ourselves from the animals, were being swept aside like leaves before a fire.`,

    // The Princess of Mars — Burroughs
    `I, John Carter, am not of this world. I was born in Virginia, fought for the Confederacy, and then, in the mountains of Arizona in the year of our Lord eighteen sixty-six, I found myself transported by means I have never fully understood to the surface of another planet altogether. That planet was Mars, though the inhabitants called it Barsoom. It was a dying world, its great seas long since dry, its forests reduced to scattered forests of strange vegetation, its air kept breathable only by the vast atmosphere factories that hummed on the plains like metallic temples. The men of Barsoom were unlike any I had known on Earth. The green men, the Tharks, were fifteen feet tall and carried four arms and a heart for warfare that put the fiercest soldier I had ever faced in the shade. Yet I found, in time, that they were not so different from men I had known. They feared, and hoped, and were capable of loyalty, and in the right circumstances even of something that resembled tenderness. It was their world that had hardened them, not their nature; and I have often thought, in the years since, that the same may be said of more creatures than we generally admit.`,

    `The thin Martian air rushed past my face as I rode the great thoat across the dead sea bottom, the ruins of an ancient city visible on the horizon, their towers no longer proud but worn smooth by ten thousand years of wind. Dejah Thoris rode beside me, and I was aware every moment of the trust she placed in me, a stranger from a distant world she could barely imagine. She had explained to me, with a patience I found remarkable given her peril, the ancient history of Barsoom: how the seas had dried, how the atmosphere had thinned, how city after city had fallen into silence. And yet her people had endured. They had found ways to survive in a world that was slowly dying beneath them, and in that survival there was something I could not help but admire, even as I fought to escape it. She turned to look at me then, and her eyes were dark and intelligent and completely unafraid, and I knew I would do whatever the world required of me to keep her safe.`,

    // Dracula — Stoker
    `I must have been asleep when I found the letters. They were tied with a thin red ribbon, old and frayed, and the handwriting on the envelopes was in a language I did not recognise. Mina said I should not open them, that they were not addressed to me, that they had been locked away for a reason. But reason had been in short supply in that house from the moment we arrived. The servants left every evening before dark and did not return until after sunrise. The master was not to be disturbed after sunset. The east wing was locked and had been so for years, we were told, since a structural fault had made it unsafe. We accepted these explanations the way one accepts the terms of a contract written in a foreign language: uneasily, and only because there seemed to be no alternative. But I am a methodical woman, and when I find a locked door, I have never been content to simply walk past it. I tried the letters. I tried the east wing. I tried everything I had been told to leave alone. And eventually everything I had been told to leave alone answered me, and I wish with all my heart that it had not.`,

    `The Professor spread his papers on the table with the confidence of a man who has long since ceased to be surprised by the things his profession requires him to believe. He spoke quietly and without drama, setting out facts with the same manner he might use to describe the symptoms of an ordinary fever. There was a creature, he said, that had lived for centuries by drinking the blood of the living. That creature had a name, and a history, and a castle in Transylvania, and it had come now to England. The room was silent when he finished. Then one of the younger men laughed, briefly, and immediately stopped laughing. The Professor did not appear to notice the laughter. He was already rolling up his papers, preparing for the next stage of his explanation, which would require them to believe something even more unlikely. I looked around the table at the faces of my companions, all of them intelligent, all of them trained to reason, and saw in each of them the same expression: the expression of a person who has just discovered that the category they put things in when they did not want to think about them any further has been opened, and found to contain something real.`,

    // Sherlock Holmes — Doyle
    `The case of the Speckled Band remains, in my judgment, the most dangerous investigation that Holmes and I ever undertook, and were it not for the fact that our client's need was so pressing, I believe even Holmes might have declined to pursue it to its conclusion. The facts, as they were told to us in Baker Street on a cold spring morning, were these: Miss Helen Stoner had come to us in a state of considerable terror, her face white and drawn, her eyes haunted by something that had kept her from sleep for several nights together. Her stepfather, she told us, was Dr. Grimesby Roylott, once a physician of great promise, now a man who had spent years in India and returned with a temper that made him notorious throughout the county of Surrey. He kept strange animals on his estate, creatures brought back from the east, and his neighbours had learned to avoid the grounds after dark. Helen's twin sister Julia had died two years before in the room next to the one Helen herself now occupied, under circumstances that the local coroner had been unable to satisfactorily explain. Julia's last words, spoken as she lay dying in Helen's arms, had been a reference to a speckled band.`,

    `I had not seen Holmes for several days when he appeared at my door late on a Thursday evening, hatless and with mud on his coat, his face carrying that particular expression of contained excitement that I had learned to read as the sign of a case reaching its climax. He refused my offer of a chair and paced the length of my consulting room twice before stopping at the window and looking out into the dark street below. Watson, he said, without turning, I want you to come with me tonight. I cannot tell you where we are going, and I cannot tell you what we expect to find, because I may be entirely wrong and I would rather not have your expectations spoil the observation. I will only tell you this: if I am right, tonight's work will resolve a question that has puzzled Scotland Yard for six months, and settle the fate of a man who is at present under sentence of death for a crime he did not commit. I had already reached for my coat. That was often how it was with Holmes. You did not weigh the proposition; you simply went.`,

    `The science of detection is not, as many suppose, a matter of dramatic inspiration. It is, rather, a discipline as rigorous and painstaking as any in the natural sciences, and its results are obtained by exactly the same means: careful observation, accurate recording of facts, formation of hypotheses, and the ruthless discarding of those hypotheses when the facts do not support them. I have heard it said that genius consists of seeing what others overlook. That is only partly true. Genius in this field consists of seeing what others overlook and then refusing, absolutely, to allow what one wishes to see to replace what is actually there. I have known investigators — and I do not exclude myself from this criticism in my earlier years — who allowed their theories to run ahead of their evidence. The result is always the same. The theory becomes a prison, and the detective ends by ignoring everything that does not fit within its walls. The truth is not inside the walls. It is usually found in the precise detail that one was most tempted to set aside.`,

    `Baker Street in the early evening had a character all its own. The day's business was done, the cabs fewer, the street lamps newly lit and sending their yellow circles down onto the wet pavement. I had walked from my club through a light rain and was glad of the fire when I came into our rooms. Holmes was at his chemistry bench, apparently absorbed, but he greeted me without looking up by saying that I had dined at the club rather than at home tonight, that I had passed a pleasant enough evening without being wholly satisfied with the conversation, and that on the way home I had decided to stop in because I had something on my mind that I had not yet decided whether to speak. I asked him, as I always did at moments like this, how he could possibly know such things. He said, as he always did, that it was perfectly simple, and proceeded to explain it in a manner that made it seem both perfectly simple and completely extraordinary, two qualities that, in Holmes, almost always came together.`,

    `There are cases that never leave you. The logician in Holmes would say that sentiment has no place in the work, and he would be right in the way that a properly constructed argument is right: formally correct, and yet somehow insufficient to account for the full reality of things. I have forgotten the precise details of a hundred cases I have recorded. But I have never forgotten the face of the woman who came to us in Baker Street in the middle of a November night, with rain in her hair and fear in her eyes and a story that neither Holmes nor I could have invented. I have never forgotten the long hours of waiting, the drive through the frozen countryside, the moment when Holmes struck the match and the solution to everything was suddenly, brilliantly visible. And I have never forgotten what it cost us, that clarity. Some of the things one learns in the practice of detection are things one would rather not know. Holmes has said as much to me, in his way. It is the price of seeing clearly, he told me once. And I suppose it is. But the price is not nothing, and anyone who tells you otherwise has never paid it.`,
  ],
};
